version: '3.8'

services:
  agri-ai:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - BHUVAN_API_KEY=${BHUVAN_API_KEY}
    depends_on:
      - postgres
    networks:
      - agri-ai-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=agri_ai
      - POSTGRES_USER=agri_user
      - POSTGRES_PASSWORD=agri_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - agri-ai-network

volumes:
  postgres_data:

networks:
  agri-ai-network:
    driver: bridge
